routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\WebsiteController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DesignController;
use App\Http\Controllers\ConstructionController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\PortfolioController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\PostContenidosController;
use App\Http\Controllers\MailController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [WebsiteController::class, 'home'])->name('website.home');
Route::get('/construction', [WebsiteController::class, 'construction'])->name('website.construction');
Route::get('/contact', [WebsiteController::class, 'contact'])->name('website.contact');
Route::get('/design', [WebsiteController::class, 'design'])->name('website.design');
Route::get('/journal', [WebsiteController::class, 'journal'])->name('website.journal');
Route::get('/posts/{post}', [WebsiteController::class, 'post'])->name('website.post');
Route::get('/portfolio', [WebsiteController::class, 'portfolio'])->name('website.portfolio');
Route::get('/viewer', [WebsiteController::class, 'viewer'])->name('website.viewer');
Route::post('/mail', [MailController::class, 'sendMail'])->name('website.sendMail');
Route::get('/test', [WebsiteController::class, 'test'])->name('website.test');

Route::prefix('/admin')->group(function() {
  Route::get('/', function() {
    if(Auth::check())
    {
      return redirect()->route('users.index');
    }
    return redirect()->route('login.index');
  });

  Route::get('/login', [LoginController::class, 'index'])->name('login.index');
  Route::post('/login', [LoginController::class, 'login'])->name('login.login');
  Route::get('/logout', [LoginController::class, 'logout'])->name('logout');

  Route::resource('users', UsersController::class);

  Route::get('/home', [HomeController::class, 'index'])->name('home.index');
  Route::get('/home/edit', [HomeController::class, 'edit'])->name('home.edit');
  Route::put('/home', [HomeController::class, 'update'])->name('home.update');

  Route::get('/design', [DesignController::class, 'index'])->name('design.index');
  Route::get('/design/edit', [DesignController::class, 'edit'])->name('design.edit');
  Route::put('/design', [DesignController::class, 'update'])->name('design.update');

  Route::get('/construction', [ConstructionController::class, 'index'])->name('construction.index');
  Route::get('/construction/edit', [ConstructionController::class, 'edit'])->name('construction.edit');
  Route::put('/construction', [ConstructionController::class, 'update'])->name('construction.update');

  Route::get('/contact', [ContactController::class, 'index'])->name('contact.index');
  Route::get('/contact/edit', [ContactController::class, 'edit'])->name('contact.edit');
  Route::put('/contact', [ContactController::class, 'update'])->name('contact.update');

  Route::get('/portfolio', [PortfolioController::class, 'index'])->name('portfolio.index');
  Route::post('/portfolio', [PortfolioController::class, 'store'])->name('portfolio.store');
  Route::delete('/portfolio/{image}', [PortfolioController::class, 'destroy'])->name('portfolio.destroy');

  Route::resource('posts', PostsController::class)->except('edit');
  Route::resource('post_contenidos', PostContenidosController::class)->only('store', 'update', 'destroy');
  Route::post('/post_contenidos/{post_contenido}', [PostContenidosController::class, 'update'])->name('post_contenidos.update2');
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
  use HasFactory;

  /**
   * The attributes that are not mass assignable.
   *
   * @var array
   */
  protected $guarded = ['id'];

  public function contenidos()
  {
    return $this->hasMany(Post_contenido::class, 'post_id', 'id');
  }

  public function getFotosAttribute()
  {
    return $this->contenidos()->where('tipo', 'FOTO')->get();
  }

  public function getTextosAttribute()
  {
    return $this->contenidos()->where('tipo', 'TEXTO')->get();
  }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Models\Post_contenido;
use App\Http\Resources\PostContenidoResource;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Validator;

class PostsController extends Controller
{
  public function __construct()
  {
    $this->middleware('auth');
  }

  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    $posts = Post::get();
    return view('posts.index', compact('posts'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    return view('posts.create');
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $req)
  {
    $rules = [
      'title' => 'required|string|min:3|max:255|unique:posts'
    ];
    
    $messages = [
      'required' => 'El campo "Título" es requerido.',
      'min' => 'El título debe tener por lo menos 3 caracteres.',
      'unique' => 'Ya existe un Post con este título.'
    ];

    $validator = Validator::make($req->all(), $rules, $messages)->validate();

    $post = Post::create([
      'title' => $req->title
    ]);

    $folder = public_path('assets/img/posts').'/post_'.$post->id;
    File::makeDirectory($folder, 0777, true, true);

    return response()->json([
      'message' => 'El Post se registró exitosamente.',
      'post_id' => $post->id
    ]);
  }

  /**
   * Display the specified resource.
   *
   * @param  \App\Models\Post  $post
   * @return \Illuminate\Http\Response
   */
  public function show(Post $post)
  {
    $post->load('contenidos');
    $contenidos = PostContenidoResource::collection($post->contenidos);
    return view('posts.show', compact('post', 'contenidos'));
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  \App\Models\Post  $post
   * @return \Illuminate\Http\Response
   */
  public function edit(Post $post)
  {
    $post->load('contenidos');
    $contenidos = PostContenidoResource::collection($post->contenidos);
    return view('posts.edit', compact('post', 'contenidos'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  \App\Models\Post  $post
   * @return \Illuminate\Http\Response
   */
  public function update(Request $req, Post $post)
  {
    if($req->title)
    {
      $rules = [
        'title' => 'required|string|min:3|max:255|unique:posts,title,'.$post->id
      ];
      $messages = [
        'required' => 'El campo "Título" es requerido.',
        'min' => 'El título debe tener por lo menos 3 caracteres.',
        'unique' => 'Ya existe un Post con este título.'
      ];
      $validator = Validator::make($req->all(), $rules, $messages)->validate();

      $post->update([
        'title' => $req->title
      ]);

      return response()->json([
        'message' => 'El Post fue actualizado exitosamente.'
      ]);
    }
    if($req->fecha)
    {
      $rules = [
        'fecha' => 'sometimes|date'
      ];
      $messages = [
        'date' => 'El valor de la fecha no es válido.',
        'min' => 'El título debe tener por lo menos 3 caracteres.',
        'unique' => 'Ya existe un Post con este título.'
      ];
      $validator = Validator::make($req->all(), $rules, $messages)->validate();

      $post->update([
        'fecha' => $req->fecha
      ]);

      return response()->json([
        'message' => 'El Post fue actualizado exitosamente.'
      ]);
    }

    return response()->json([
      'message' => 'El Post no fue actualizado.'
    ]);
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  \App\Models\Post  $post
   * @return \Illuminate\Http\Response
   */
  public function destroy(Post $post)
  {
    $folder = public_path('assets/img/posts').'/post_'.$post->id;
    $contenidos = $post->contenidos;
    foreach($contenidos as $cnt)
    {
      if($cnt->tipo == 'FOTO')
      {
        File::delete("$folder/$cnt->foto");
      }
      $cnt->delete();
    }
    $post->delete();
    
    return redirect()->route('posts.index')->with('success', 'El post fue removido exitosamente.');
  }
}

resources/views/posts/create.blade.php
@extends ('layouts.master')

@section ('styles')

<!-- vendor css -->
<link href="/bracketv2/lib/font-awesome/css/font-awesome.css" rel="stylesheet">
<link href="/bracketv2/lib/Ionicons/css/ionicons.css" rel="stylesheet">
<link href="/bracketv2/lib/perfect-scrollbar/css/perfect-scrollbar.css" rel="stylesheet">
<link href="/bracketv2/lib/jquery-switchbutton/jquery.switchButton.css" rel="stylesheet">
<link href="/bracketv2/lib/highlightjs/github.css" rel="stylesheet">

<style>
form .form-layout input.is-invalid {
  border: 1px solid #dc3545 !important;
}

button:hover {
  cursor: pointer;
}
</style>

@endsection

@section ('pageheader')

<div class="br-pageheader pd-y-15 pd-l-20">
  <nav class="breadcrumb pd-0 mg-0 tx-12">
    <a class="breadcrumb-item" href="{{ route('posts.index') }}">Posts</a>
    <span class="breadcrumb-item active">Creación de Post</span>
  </nav>
</div><!-- br-pageheader -->

<div class="pd-x-20 pd-sm-x-30 pd-t-20 pd-sm-t-30">
  <h4 class="tx-gray-800 mg-b-5">Posts</h4>
  <p class="mg-b-0">Creación de Posts</p>
</div>

@endsection

@section ('contentpanel')

@include('layouts._errors')
@include('layouts._messages')

<div class="br-section-wrapper">
  <h6 class="tx-gray-800 tx-uppercase tx-bold tx-24 mg-b-30 section-title">
    Nuevo Post
  </h6>
  @php
    $title = old('title', '');
    $fecha = old('fecha', date('d-m-Y'));
    $perrors = $errors->isEmpty() ? null : $errors;
  @endphp
  <post-page ptitle="{{ $title }}" pfecha="{{ $fecha }}"></post-page>
</div><!-- br-section-wrapper -->

@endsection

@section ('scripts')

<script src="/bracketv2/lib/jquery/jquery.js"></script>
<script src="/bracketv2/lib/popper.js/popper.js"></script>
<script src="/bracketv2/lib/bootstrap/bootstrap.js"></script>
<script src="/bracketv2/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.js"></script>
<script src="/bracketv2/lib/moment/moment.js"></script>
<script src="/bracketv2/lib/jquery-ui/jquery-ui.js"></script>
<script src="/bracketv2/lib/jquery-switchbutton/jquery.switchButton.js"></script>
<script src="/bracketv2/lib/peity/jquery.peity.js"></script>
<script src="/bracketv2/lib/highlightjs/highlight.pack.js"></script>

@endsection

resources/views/posts/edit.blade.php
@extends ('layouts.master')

@section ('styles')

<!-- vendor css -->
<link href="/bracketv2/lib/font-awesome/css/font-awesome.css" rel="stylesheet">
<link href="/bracketv2/lib/Ionicons/css/ionicons.css" rel="stylesheet">
<link href="/bracketv2/lib/perfect-scrollbar/css/perfect-scrollbar.css" rel="stylesheet">
<link href="/bracketv2/lib/jquery-switchbutton/jquery.switchButton.css" rel="stylesheet">
<link href="/bracketv2/lib/highlightjs/github.css" rel="stylesheet">

<style>
form .form-layout input.is-invalid {
  border: 1px solid #dc3545 !important;
}

button:hover {
  cursor: pointer;
}
</style>

@endsection

@section ('pageheader')

<div class="br-pageheader pd-y-15 pd-l-20">
  <nav class="breadcrumb pd-0 mg-0 tx-12">
    <a class="breadcrumb-item" href="{{ route('users.index') }}">Usuarios</a>
    <span class="breadcrumb-item active">Edición de Usuario</span>
  </nav>
</div><!-- br-pageheader -->

<div class="pd-x-20 pd-sm-x-30 pd-t-20 pd-sm-t-30">
  <h4 class="tx-gray-800 mg-b-5">Usuario de Sistema</h4>
  <p class="mg-b-0">Edición de Usuario</p>
</div>

@endsection

@section ('contentpanel')

@include('layouts._errors')
@include('layouts._messages')

<div class="br-section-wrapper">
  <h6 class="tx-gray-800 tx-uppercase tx-bold tx-24 mg-b-30 section-title">
    Editar Post
  </h6>
  @php
    $title = old('title', $post->title);
    $fecha = old('fecha', date('d-m-Y', strtotime($post->fecha)));
    $perrors = $errors->isEmpty() ? null : $errors;
  @endphp
  {{-- <edit-post-page ptitle="{{ $title }}" pfecha="{{ $fecha }}" :contenidos="{{ json_encode($contenidos) }}"></edit-post-page> --}}
</div><!-- br-section-wrapper -->

@endsection

@section ('scripts')

<script src="/bracketv2/lib/jquery/jquery.js"></script>
<script src="/bracketv2/lib/popper.js/popper.js"></script>
<script src="/bracketv2/lib/bootstrap/bootstrap.js"></script>
<script src="/bracketv2/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.js"></script>
<script src="/bracketv2/lib/moment/moment.js"></script>
<script src="/bracketv2/lib/jquery-ui/jquery-ui.js"></script>
<script src="/bracketv2/lib/jquery-switchbutton/jquery.switchButton.js"></script>
<script src="/bracketv2/lib/peity/jquery.peity.js"></script>
<script src="/bracketv2/lib/highlightjs/highlight.pack.js"></script>

@endsection

resources/views/posts/index.blade.php
@extends ('layouts.master')

@section ('styles')

<!-- vendor css -->
<link href="/bracketv2/lib/font-awesome/css/font-awesome.css" rel="stylesheet">
<link href="/bracketv2/lib/Ionicons/css/ionicons.css" rel="stylesheet">
<link href="/bracketv2/lib/perfect-scrollbar/css/perfect-scrollbar.css" rel="stylesheet">
<link href="/bracketv2/lib/jquery-switchbutton/jquery.switchButton.css" rel="stylesheet">
<link href="/bracketv2/lib/highlightjs/github.css" rel="stylesheet">
<link href="/bracketv2/lib/datatables/jquery.dataTables.css" rel="stylesheet">
<link href="/bracketv2/lib/select2/css/select2.min.css" rel="stylesheet">

<style>
.section-title {
  display: flex; 
  justify-content: space-between; 
  align-items: center
}
.table td {
  vertical-align: middle !important;
}
button:hover {
  cursor: pointer;
}
</style>

@endsection

@section ('pageheader')

<div class="br-pageheader pd-y-15 pd-l-20">
  <nav class="breadcrumb pd-0 mg-0 tx-12">
    <span class="breadcrumb-item active">Posts</span>
  </nav>
</div><!-- br-pageheader -->

<div class="pd-x-20 pd-sm-x-30 pd-t-20 pd-sm-t-30">
  <h4 class="tx-gray-800 mg-b-5">Posts</h4>
</div>

@endsection

@section ('contentpanel')

@include('layouts._errors')
@include('layouts._messages')

<div class="br-section-wrapper">
  <h6 class="tx-gray-800 tx-uppercase tx-bold tx-24 mg-b-30 section-title">
    Posts
    <create-post></create-post>
  </h6>
  <div class="table-wrapper">
    <table class="table table-striped responsive compact" id="posts" style="width: 100%;">
      <thead>
        <tr>
          <th>Título</th>
          <th>Fotos</th>
          <th>Párrafos</th>
          <th>Fecha</th>
          <th>Actualizado en</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      @foreach ($posts as $post)
        <tr>
          <td>{{ $post->title }}</td>
          <td>{{ count($post->fotos) }}</td>
          <td>{{ count($post->textos) }}</td>
          <td>{{ $post->fecha }}</td>
          <td>{{ date('d/M/Y h:i a', strtotime($post->updated_at)) }}</td>
          <td class="table-action">
            <div class="row flex-nowrap">
              <div class="col text-center">
                <a href="{{ route('posts.show', $post->id) }}" class="btn btn-outline-info btn-sm">
                  <i class="fa fa-eye"></i>
                </a>
              </div>
              {{-- <div class="col text-center">
                <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-outline-warning btn-sm">
                  <i class="fa fa-pencil"></i>
                </a>
              </div> --}}
              <div class="col text-center">
                <form action="{{ route('posts.destroy', $post->id) }}" method="POST" class="delete" data-name="{{ $post->title }}">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-outline-dark btn-sm delete-row">
                    <i class="fa fa-trash-o"></i>
                  </button>
                </form>
              </div>
            </div>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div><!-- table-wrapper -->
</div><!-- br-section-wrapper -->

@endsection

@section ('scripts')

<script src="/bracketv2/lib/jquery/jquery.js"></script>
<script src="/bracketv2/lib/popper.js/popper.js"></script>
<script src="/bracketv2/lib/bootstrap/bootstrap.js"></script>
<script src="/bracketv2/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.js"></script>
<script src="/bracketv2/lib/moment/moment.js"></script>
<script src="/bracketv2/lib/jquery-ui/jquery-ui.js"></script>
<script src="/bracketv2/lib/jquery-switchbutton/jquery.switchButton.js"></script>
<script src="/bracketv2/lib/peity/jquery.peity.js"></script>
<script src="/bracketv2/lib/highlightjs/highlight.pack.js"></script>
<script src="/bracketv2/lib/datatables/jquery.dataTables.js"></script>
<script src="/bracketv2/lib/datatables-responsive/dataTables.responsive.js"></script>
<script src="/bracketv2/lib/select2/js/select2.min.js"></script>

@endsection

@section ('jquery')

<script>
jQuery(document).ready(function() {

  "use strict";

  $('#posts').DataTable({
    responsive: true,
    language: {
      emptyTable: "No se encontraron registros",
      info: "Mostrando registros _START_ a _END_ de _TOTAL_",
      infoEmpty: "Mostrando registros 0 a 0 de 0",
      infoFiltered: "(Filtrado de _MAX_ registros)",
      lengthMenu: '_MENU_ elementos por página',
      loadingRecords: "Cargando...",
      processing: "Procesando...",
      search: "",
      searchPlaceholder: 'Buscar...',
      zeroRecords: "No se encontraron registros",
      paginate: {
        first: "Primera",
        last: "Última",
        next: "Siguiente",
        previous: "Anterior"
      },
      aria: {
        sortAscending: ": Orden ascendente",
        sortDescending: ": Orden descendente"
      }
    }
  });

   // Select2
  jQuery('select').select2();

  $("form.delete").submit(function(event) {
    var name = $(this).data("name");
    var sure = confirm(`¿Desea remover el Post con título ${name}?`);
    if(!sure)
    {
      event.preventDefault();
    }
  });

});
</script>
@endsection

resources/views/posts/show.blade.php
@extends ('layouts.master')

@section ('styles')

<!-- vendor css -->
<link href="/bracketv2/lib/font-awesome/css/font-awesome.css" rel="stylesheet">
<link href="/bracketv2/lib/Ionicons/css/ionicons.css" rel="stylesheet">
<link href="/bracketv2/lib/perfect-scrollbar/css/perfect-scrollbar.css" rel="stylesheet">
<link href="/bracketv2/lib/jquery-switchbutton/jquery.switchButton.css" rel="stylesheet">
<link href="/bracketv2/lib/highlightjs/github.css" rel="stylesheet">

<style>
button:hover {
  cursor: pointer;
}
.image-container {
  height: 100px;
  width: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  margin: 5px;
}
.foto {
  max-width: 100%;
  max-height: 100%;
}
</style>

@endsection

@section ('pageheader')

<div class="br-pageheader pd-y-15 pd-l-20">
  <nav class="breadcrumb pd-0 mg-0 tx-12">
    <a class="breadcrumb-item" href="{{ route('posts.index') }}">Posts</a>
    <span class="breadcrumb-item active">Revisar Post</span>
  </nav>
</div><!-- br-pageheader -->

<div class="pd-x-20 pd-sm-x-30 pd-t-20 pd-sm-t-30">
  <h4 class="tx-gray-800 mg-b-5">Posts</h4>
  <p class="mg-b-0">Revisar Post</p>
</div>

@endsection

@section ('contentpanel')

@include('layouts._errors')
@include('layouts._messages')

<div class="br-section-wrapper">
  <h6 class="tx-gray-800 tx-uppercase tx-bold tx-24 mg-b-30 section-title">
    Post
  </h6>
  <post-page :ppost="{{ $post }}" :pcontenidos="{{ json_encode($contenidos) }}"></post-page>
</div><!-- br-section-wrapper -->

@endsection

@section ('scripts')

<script src="/bracketv2/lib/jquery/jquery.js"></script>
<script src="/bracketv2/lib/popper.js/popper.js"></script>
<script src="/bracketv2/lib/bootstrap/bootstrap.js"></script>
<script src="/bracketv2/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.js"></script>
<script src="/bracketv2/lib/moment/moment.js"></script>
<script src="/bracketv2/lib/jquery-ui/jquery-ui.js"></script>
<script src="/bracketv2/lib/jquery-switchbutton/jquery.switchButton.js"></script>
<script src="/bracketv2/lib/peity/jquery.peity.js"></script>
<script src="/bracketv2/lib/highlightjs/highlight.pack.js"></script>

@endsection