routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\WebsiteController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DesignController;
use App\Http\Controllers\ConstructionController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\PortfolioController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\PostContenidosController;
use App\Http\Controllers\MailController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [WebsiteController::class, 'home'])->name('website.home');
Route::get('/construction', [WebsiteController::class, 'construction'])->name('website.construction');
Route::get('/contact', [WebsiteController::class, 'contact'])->name('website.contact');
Route::get('/design', [WebsiteController::class, 'design'])->name('website.design');
Route::get('/journal', [WebsiteController::class, 'journal'])->name('website.journal');
Route::get('/posts/{post}', [WebsiteController::class, 'post'])->name('website.post');
Route::get('/portfolio', [WebsiteController::class, 'portfolio'])->name('website.portfolio');
Route::get('/viewer', [WebsiteController::class, 'viewer'])->name('website.viewer');
Route::post('/mail', [MailController::class, 'sendMail'])->name('website.sendMail');
Route::get('/test', [WebsiteController::class, 'test'])->name('website.test');

Route::prefix('/admin')->group(function() {
  Route::get('/', function() {
    if(Auth::check())
    {
      return redirect()->route('users.index');
    }
    return redirect()->route('login.index');
  });

  Route::get('/login', [LoginController::class, 'index'])->name('login.index');
  Route::post('/login', [LoginController::class, 'login'])->name('login.login');
  Route::get('/logout', [LoginController::class, 'logout'])->name('logout');

  Route::resource('users', UsersController::class);

  Route::get('/home', [HomeController::class, 'index'])->name('home.index');
  Route::get('/home/edit', [HomeController::class, 'edit'])->name('home.edit');
  Route::put('/home', [HomeController::class, 'update'])->name('home.update');

  Route::get('/design', [DesignController::class, 'index'])->name('design.index');
  Route::get('/design/edit', [DesignController::class, 'edit'])->name('design.edit');
  Route::put('/design', [DesignController::class, 'update'])->name('design.update');

  Route::get('/construction', [ConstructionController::class, 'index'])->name('construction.index');
  Route::get('/construction/edit', [ConstructionController::class, 'edit'])->name('construction.edit');
  Route::put('/construction', [ConstructionController::class, 'update'])->name('construction.update');

  Route::get('/contact', [ContactController::class, 'index'])->name('contact.index');
  Route::get('/contact/edit', [ContactController::class, 'edit'])->name('contact.edit');
  Route::put('/contact', [ContactController::class, 'update'])->name('contact.update');

  Route::get('/portfolio', [PortfolioController::class, 'index'])->name('portfolio.index');
  Route::post('/portfolio', [PortfolioController::class, 'store'])->name('portfolio.store');
  Route::delete('/portfolio/{image}', [PortfolioController::class, 'destroy'])->name('portfolio.destroy');

  Route::resource('posts', PostsController::class)->except('edit');
  Route::resource('post_contenidos', PostContenidosController::class)->only('store', 'update', 'destroy');
  Route::post('/post_contenidos/{post_contenido}', [PostContenidosController::class, 'update'])->name('post_contenidos.update2');
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
  use HasFactory;

  /**
   * The attributes that are not mass assignable.
   *
   * @var array
   */
  protected $guarded = ['id'];

  public function contenidos()
  {
    return $this->hasMany(Post_contenido::class, 'post_id', 'id');
  }

  public function getFotosAttribute()
  {
    return $this->contenidos()->where('tipo', 'FOTO')->get();
  }

  public function getTextosAttribute()
  {
    return $this->contenidos()->where('tipo', 'TEXTO')->get();
  }
}

app/Models/Post_contenido.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post_contenido extends Model
{
  use HasFactory;

  /**
   * The attributes that are not mass assignable.
   *
   * @var array
   */
  protected $guarded = ['id'];

  public function post()
  {
    return $this->belongsTo(Post::class, 'post_id', 'id');
  }

  public function getUrlAttribute()
  {
    return $this->tipo == 'FOTO' ? '/assets/img/posts/post_'.$this->post->id.'/'.$this->foto : null;
  }
}

app/Http/Controllers/WebsiteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Image;
use App\Models\Configuracion;
use App\Models\Post;

class WebsiteController extends Controller
{
  public function home()
  {
    $img_principal = Image::where('seccion', 'HOME')
    ->where('tipo', 'PRINCIPAL')
    ->first();

    $img_muestra = Image::where('seccion', 'HOME')
    ->where('tipo', 'MUESTRA')
    ->take(4)
    ->get();

    $img_galeria = Image::where('seccion', 'HOME')
    ->where('tipo', 'GALERIA')
    ->take(6)
    ->get();

    $config = Configuracion::first();

    return view('website.home', compact('img_principal', 'img_muestra', 'img_galeria', 'config'));
  }

  public function construction()
  {
    $img_principal = Image::where('seccion', 'CONSTRUCTION')
    ->where('tipo', 'PRINCIPAL')
    ->first();

    $img_proyecto = Image::where('seccion', 'CONSTRUCTION')
    ->where('tipo', 'PROYECTO')
    ->take(2)
    ->get();

    $config = Configuracion::first();

    return view('website.construction', compact('img_principal', 'img_proyecto', 'config'));
  }

  public function contact()
  {
    $img_principal = Image::where('seccion', 'CONTACT')
    ->where('tipo', 'PRINCIPAL')
    ->first();

    $config = Configuracion::first();
    
    return view('website.contact', compact('img_principal', 'config'));
  }

  public function design()
  {
    $img_principal = Image::where('seccion', 'DESIGN')
    ->where('tipo', 'PRINCIPAL')
    ->first();

    $img_proyecto = Image::where('seccion', 'DESIGN')
    ->where('tipo', 'PROYECTO')
    ->take(2)
    ->get();

    $config = Configuracion::first();

    return view('website.design', compact('img_principal', 'img_proyecto', 'config'));
  }

  public function journal()
  {
    $posts = Post::with('contenidos')->orderByDesc('fecha')->get();

    $config = Configuracion::first();

    return view('website.journal', compact('posts', 'config'));
  }

  public function post(Post $post)
  {
    $config = Configuracion::first();

    $next_post = Post::orderBy('fecha')->where('fecha', '>', $post->fecha)->first();
    if($next_post)
    {
      $next = route('website.post', $next_post->id);
    }
    else
    {
      $next = route('website.post', Post::orderBy('fecha')->first()->id);
    }
    $prev_post = Post::orderByDesc('fecha')->where('fecha', '<', $post->fecha)->first();
    if($prev_post)
    {
      $prev = route('website.post', $prev_post->id);
    }
    else {
      $prev = route('website.post', Post::orderByDesc('fecha')->first()->id);
    }
    
    return view('website.post', compact('post', 'config', 'prev', 'next'));
  }

  public function portfolio()
  {
    $images = Image::where('seccion', 'PORTFOLIO')->get();

    $config = Configuracion::first();

    return view('website.portfolio', compact('images', 'config'));
  }

  public function viewer()
  {
    $images = Image::where('seccion', 'PORTFOLIO')->get();

    $config = Configuracion::first();

    return view('website.viewer', compact('images', 'config'));
  }

  public function test()
  {
    return view('website.test');
  }
}

resources/views/website/construction.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
            integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
            crossorigin="anonymous"
        />
        <link rel="stylesheet" href="{{ asset('/assets/construction.css') }}" />
        <link
            rel="stylesheet"
            type="text/css"
            href="{{ asset('/assets/Montserrat font/stylesheet.css') }}"
        />
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
        <script src="{{ asset('/assets/navbar.js') }}"></script>
        <link
            rel="preload"
            as="font"
            href="{{ asset('/assets/Montserrat font/Montserrat-Light.woff2') }}"
            type="font/woff2"
            crossorigin="anonymous"
        />
        <link
            rel="preload"
            as="font"
            href="{{ asset('/assets/Montserrat font/Montserrat-Regular.woff2') }}"
            type="font/woff2"
            crossorigin="anonymous"
        />
        <title>DH</title>
    </head>
    <body>
        @include('website._navbar')

        <section class="sectmb">
            <div
                data-aos="newfup"
                data-aos-duration="1500"
                data-aos-easing="lineal"
                class="text-center"
            >
                <h1
                    style="font-size: 40px;"
                    class="text-center titlemarg lightmode"
                >
                    Construction
                </h1>
                <div class="mycontainer">
                    <h1 class="text-center lightmode size32">
                        Dream builders. We construct <br />
                        timeless investments for residential
                        <br class="line line-break--md-and-up" />
                        and commercial projects.
                    </h1>
                    <svg
                        width="90"
                        height="45"
                        viewBox="0 0 90 55"
                        fill="none"
                        class="gmb gmt"
                    >
                        <path
                            d="M30.7719 9.82227H16.0728V45.1777H30.7719C36.0731 45.1777 40.3911 43.548 43.6112 40.3294C46.7902 37.1517 48.4044 32.8275 48.4044 27.4959C48.4044 22.1807 46.7902 17.8483 43.603 14.6051C40.3747 11.4357 36.0567 9.82227 30.7719 9.82227ZM30.2721 40.313H21.1937V14.687H30.2721C38.482 14.687 43.1933 19.3552 43.1933 27.4959C43.1933 35.6366 38.482 40.313 30.2721 40.313Z"
                            fill="#1C1C1B"
                        />
                        <path
                            d="M73.9271 45.1777V9.82227H68.8062V24.8424H44.0618V29.658H68.8062V45.1777H73.9271Z"
                            fill="#1C1C1B"
                        />
                    </svg>
                </div>
            </div>
            <div class="myimgcontainer">
                <img
                    src="{{ $img_principal->url }}"
                    class="central-img img-fluid gmb"
                    alt="Responsive image"
                />

                <div class="mt-3 gmb">
                    <div
                        data-aos="newfup"
                        data-aos-duration="1000"
                        class="row d-flex justify-content-between"
                    >
                        <div class="col-md-6 gmb mb-md-0">
                            <p class="pr-md-5">
                                DH Design is a premium construction company
                                based in Mexicali, Mexico. We specialize in
                                construction, architecture and design. Since our
                                founding in 1995, we have completed over 70
                                projects. We call ourselves "dream builders"
                                because we provide exactly that.
                            </p>
                        </div>
                        <div class="col-md-6">
                            <p id="secondp" class="d-flex justify-content-end">
                                We are local experts with global know-how, ready
                                to undertake even the most demanding custom
                                projects in a reliable and transparent way. We
                                collaborate with an extensive network of
                                speciallists and can succesfully complete
                                projects at any scale.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="text-center pt-5 pt-md-3">
                <svg width="12" height="45" viewBox="0 0 12 45" fill="none">
                    <path
                        d="M1.77692 34.5957C-0.592253 36.9935 -0.592253 40.7463 1.7688 43.1441C2.9047 44.343 4.40572 44.9999 6.0041 44.9999C7.60247 44.9999 9.10349 44.3348 10.2313 43.1441C12.6004 40.7463 12.6004 36.9853 10.2313 34.5957C7.85399 32.1979 4.14608 32.1979 1.77692 34.5957Z"
                        fill="#1C1C1B"
                    />
                    <path
                        d="M12 0L0 0L0 12.1451L12 12.1451L12 0Z"
                        fill="#1C1C1B"
                    />
                </svg>
            </div>
        </section>

        <section>
            <h2 class="ml-lg-5 pl-4 lightmode">Construction Services</h2>
            <div class="mycontainer mt-5">
                <div class="row">
                    <div class="col-md-6">
                        <div
                            class="pb-md-4"
                            data-aos="newfup"
                            data-aos-duration="1000"
                        >
                            <h5 class="mt-4 cardtitle">01.</h5>
                            <h5 class="mt-lg-5 lightmode cardtitle">
                                Construction
                            </h5>
                            <h5 class="mt-lg-5 cardfont pr-1 pr-md-5">
                                Meticulous attention to construction detail. We
                                can deliver exceptional quality throught both
                                our local and non-local network of trusted
                                subcontractors and suppliers.
                            </h5>
                        </div>
                        <div
                            data-aos="newfup"
                            data-aos-duration="1500"
                            class="imgcont"
                        >
                            <img
                                src="{{ $img_proyecto[0]->url }}"
                                class="img-fluid"
                                alt="Responsive image"
                            />
                        </div>
                    </div>

                    <div id="projectm" class="col-md-6 ocasiontopm">
                        <div
                            class="pb-md-4"
                            data-aos="newfup"
                            data-aos-duration="1000"
                        >
                            <h5 class="mt-4 cardtitle">02.</h5>
                            <h5 class="mt-lg-5 lightmode cardtitle">
                                Project Managment
                            </h5>
                            <h5 class="mt-lg-5 cardfont">
                                We will closely monitor project costs, deadlines
                                and quality of construction. You will receive a detailed
                                cost breakdown, so that you can asess project
                                costs. When the budget is approved construction
                                begins.
                            </h5>
                        </div>
                        <div
                            data-aos="newfup"
                            data-aos-duration="1500"
                            class="imgcont"
                        >
                            <img
                                src="{{ $img_proyecto[1]->url }}"
                                class="img-fluid"
                                alt="Responsive image"
                            />
                        </div>
                    </div>
                </div>
            </div>
            <div
                data-aos="newfup"
                data-aos-duration="800"
                class="text-center sectmt sectmb"
            >
                <h2 class="book ml-4 ml-md-0 mr-4 mr-md-0">
                    We offer consulting on every step of
                    <br class="line line-break--md-and-up" />
                    the process, take care of all planning,<br
                        class="line line-break--md-and-up"
                    />
                    permissions, design and construction<br
                        class="line line-break--md-and-up"
                    />
                    of your house project.
                </h2>
            </div>
        </section>
        <ul id="mywork" class="pl-0">
            <li data-aos="newfup" data-aos-duration="1500">
                <img
                    src="{{ asset('/assets/img/def/construction/construction3.jpg') }}"
                    class="img-fluid gmb"
                    alt="Responsive image"
                />
            </li>
            <li data-aos="newfup" data-aos-duration="1000">
                <img
                    src="{{ asset('/assets/img/def/construction/construction4.jpg') }}"
                    class="img-fluid gmb"
                    alt="Responsive image"
                />
            </li>

            <li data-aos="newfup" data-aos-duration="1500">
                <img
                    src="{{ asset('/assets/img/def/construction/construction5.jpg') }}"
                    class="img-fluid gmb"
                    alt="Responsive image"
                />
            </li>
            <li data-aos="newfup" data-aos-duration="1000">
                <img
                    src="{{ asset('/assets/img/def/construction/construction6.jpg') }}"
                    class="img-fluid gmb"
                    alt="Responsive image"
                />
            </li>
            <li data-aos="newfup" data-aos-duration="1500">
                <img
                    src="{{ asset('/assets/img/def/construction/construction7.jpg') }}"
                    class="img-fluid gmb"
                    alt="Responsive image"
                />
            </li>
            <li data-aos="newfup" data-aos-duration="1000">
                <img
                    src="{{ asset('/assets/img/def/construction/construction8.jpg') }}"
                    class="img-fluid gmb"
                    alt="Responsive image"
                />
            </li>
        </ul>
        <div class="container">
            <div class="contactmt" data-aos="newfup" data-aos-duration="1000">
                <div class="row justify-content-center text-center">
                    <h2>
                        Are you ready to start <br />
                        your project?
                    </h2>
                </div>
                <div class="text-center gmt sectmb">
                    <a class="acontact" href="{{ route('website.contact') }}"
                        >Contact Us</a
                    >
                </div>
            </div>
        </div>
        @include('website._footer')

        <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
        <script>
            AOS.init();
				</script>
				
				<script>
						function myFunction(x) {
								x.classList.toggle("change");
						}

						window.addEventListener("beforeunload", function() {
								document.body.classList.add("animate-out");
						});
				</script>

        <script
            src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

resources/views/website/contact.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="no"/>
    <meta name="format-detection" content="telephone=no">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('/assets/contact.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('/assets/Montserrat font/stylesheet.css') }}">
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <script src="{{ asset('/assets/navbar.js') }}"></script>
    <link rel="preload" as="font" href="{{ asset('/assets/Montserrat font/Montserrat-Light.woff2') }}" type="font/woff2" crossorigin="anonymous">
    <link rel="preload" as="font" href="{{ asset('/assets/Montserrat font/Montserrat-Regular.woff2') }}" type="font/woff2" crossorigin="anonymous">
    <title>Contact</title>
</head>
<body>

    @include('website._navbar')

    <div class="portfoliocontainer">
    <h1 class="tittle titlemarg">Contact us</h1>
    </div>

    <div data-aos="newfup2" data-aos-duration="800" data-aos-easing="ease-in-out-sine" class="mycontainer gmt">
      <div class="row">
        <div class="col-md-6 mt-5">
          <h4 class="infocontact">
            {{ $config->contacto_telefono }}
            <br>
            {{ $config->contacto_telefono_2 }}
            <br>
            <span>{{ $config->contacto_email }}</span>
          </h4>

          <h6 class="d-none d-md-block gmt direc">
            Baja California,
            <br class="line line-break--md-and-up" />
            México
          </h6>

          <h6 class="d-md-none gmt direc">
            Baja California, <br>
            México
          </h6>

            <a style="font-size:20px;" href="https://www.facebook.com/DHDesign-472904403518385" target="_blank" class="foottag">Facebook</a><br>
            <a style="font-size: 20px;" href="https://www.instagram.com/dhconstruccion/" target="_blank" class="foottag">Instagram</a>
            
        </div>
        <div class="col-md-6 circletm">
          <img src="{{ $img_principal->url }}" class="img-fluid gmb" alt="Responsive image">
        </div>
      </div>

    </div>
      <div class="portfoliocontainer gmt">
        <h2 class="lightmode">Get in touch</h2>
      </div>

          <section class="mycontainer mt-5 sectmb">
            <form id=col class="gmt">
         
                <div class="form-row">
                <div class="form-group col-2 col-md-2"></div>
                  <div class="form-group col-md-8 contacto">
                      <input type="text" class="form-control" id="inputname" name=name placeholder="Name" required>
                  </div>
                </div>
                <div class="form-row">
                  <div class="form-group col-2 col-md-2"></div>
                    <div class="form-group col-md-8 contacto">
                      <input type="email" class="form-control" id="inputemail1" name="mail" placeholder="Email Address" required>
                    </div>
                </div>
                <div class="form-row mb-3">
                <div class="form-group col-md-2"></div>
                  <div class="form-group col-md-8 contacto">
                      <textarea class="form-control" id="inputmsg" name="msj" placeholder="Message"></textarea>
                  </div>
                </div>
                 
                <div class=" d-flex justify-content-center">
                  <button id="subbut" type="submit" name=submit class="send">Send</button>
                </div>			
            </form>
          </section>
          <section id="thanks">
            <div class="row d-flex justify-content-center">
              <span class="size38 gmb">
                Your message was sent succesfully. <br>
                Thank you. We'll be in touch shortly. <br>
              </span>
              </div>
              <div class="row d-flex justify-content-center sectmb">
                <a class="acontact" href="{{ route('website.contact') }}">Go back</a>
              </div>
            </div>
          </section>
          

          @include('website._footer')

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>

  <script>
            $("#thanks").hide();
            $(document).ready(function(){
              // Variable to hold request
            var request;
            
            // Bind to the submit event of our form
            $("#col").submit(function(event){
            
                // Prevent default posting of form - put here to work in case of errors
                event.preventDefault();
            
                // Abort any pending request
                if (request) {
                    request.abort();
                }
                // setup some local variables
                var $form = $(this);
            
                // Let's select and cache all the fields
                var $inputs = $form.find("input, select, textarea");
            
                // Serialize the data in the form
                var serializedData = $form.serialize();

                // CSRF Field
                var token = $('meta[name="csrf-token"]').attr('content'); 
            
                // Fire off the request to /form.php
                request = $.ajax({
                    url: "/mail",
                    type: "post",
                    data: serializedData,
                    headers: {
                      'X-CSRF-Token': token 
                    }
                });
            
                // Callback handler that will be called on success
                request.done(function (response, textStatus, jqXHR){
                    // Log a message to the console
                    console.log("Hooray, it worked!");
                    $("#thanks").show();
                    $("#col").hide();
                });
            
                // Callback handler that 
                request.fail(function (jqXHR, textStatus, errorThrown){
                    // Log the error to the console
                    console.error(
                        "The following error occurred: "+
                        textStatus, errorThrown
                    );
                });
            
            });
            });
            
    </script>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
      AOS.init();
    
    </script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

</body>
</html>

resources/views/website/email.blade.php
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400' rel='stylesheet' type='text/css'>
<div style='color: #1c1c1b; text-align: center; background-color: #cacab0; font-family: Open Sans'>
  <img src='/img/empresa/logo_dh.png'>
  <p style='font-size: 28px; line-height: 0px;margin-top: 100px;'>Thank you!</p>
  <p style='font-size: 28px;'>
    We got your message and will <br>
    contact you shortly.
  </p>
  <img style='margin-top: 4rem;' src='/img/empresa/logo_compact.png'>
  <p style='font-size: 18px;'>Construction and Design</p>
  <div style='height: 60px;'></div>
</div>

resources/views/website/journal.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('/assets/journal.css') }}" />
    <link rel="preload" as="font" href="{{ asset('/assets/Montserrat font/Montserrat-Light.woff2') }}" type="font/woff2" crossorigin="anonymous">
    <link rel="preload" as="font" href="{{ asset('/assets/Montserrat font/Montserrat-Regular.woff2') }}" type="font/woff2" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ asset('/assets/Montserrat font/stylesheet.css') }}">
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <script src="{{ asset('/assets/navbar.js') }}"></script>
    <link rel="preload" as="font" href="{{ asset('/assets/Montserrat font/Montserrat-Light.woff2') }}" type="font/woff2" crossorigin="anonymous">
    <link rel="preload" as="font" href="{{ asset('/assets/Montserrat font/Montserrat-Regular.woff2') }}" type="font/woff2" crossorigin="anonymous">
    <title>DH</title>
</head>
<body class="animate-in">

  @include('website._navbar')

    <div class="portfoliocontainer">
      <h1 class="book tittle titlemarg">Journal</h1>
    </div>

    <ul id="mywork" class="pl-0">
      @forelse($posts as $post)
        <li>
          <a href="{{ route('website.post', $post->id) }}">
            @if(count($post->fotos))
              <img src="{{ $post->fotos[0]->url }}" class="img-fluid" alt="Responsive image">
            @endif
          </a>
          <p>{{ $post->title }}</p>
        </li>
      @empty
        <li>
          <p class="text-center">There are no posts!</p>
        </li>
      @endforelse
    </ul>

    @include('website._footer')



    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
      AOS.init();
    
    </script>
    <script>
      function myFunction(x) {
        x.classList.toggle("change");
      }
      window.addEventListener("beforeunload", function () {
        document.body.classList.add("animate-out");
      });
    </script>

    <script>
      firstimg=document.querySelector("img");
      firstimg.classList.add("expand-img");
    </script>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>