routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\WebsiteController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DesignController;
use App\Http\Controllers\ConstructionController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\PortfolioController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\PostContenidosController;
use App\Http\Controllers\MailController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [WebsiteController::class, 'home'])->name('website.home');
Route::get('/construction', [WebsiteController::class, 'construction'])->name('website.construction');
Route::get('/contact', [WebsiteController::class, 'contact'])->name('website.contact');
Route::get('/design', [WebsiteController::class, 'design'])->name('website.design');
Route::get('/journal', [WebsiteController::class, 'journal'])->name('website.journal');
Route::get('/posts/{post}', [WebsiteController::class, 'post'])->name('website.post');
Route::get('/portfolio', [WebsiteController::class, 'portfolio'])->name('website.portfolio');
Route::get('/viewer', [WebsiteController::class, 'viewer'])->name('website.viewer');
Route::post('/mail', [MailController::class, 'sendMail'])->name('website.sendMail');
Route::get('/test', [WebsiteController::class, 'test'])->name('website.test');

Route::prefix('/admin')->group(function() {
  Route::get('/', function() {
    if(Auth::check())
    {
      return redirect()->route('users.index');
    }
    return redirect()->route('login.index');
  });

  Route::get('/login', [LoginController::class, 'index'])->name('login.index');
  Route::post('/login', [LoginController::class, 'login'])->name('login.login');
  Route::get('/logout', [LoginController::class, 'logout'])->name('logout');

  Route::resource('users', UsersController::class);

  Route::get('/home', [HomeController::class, 'index'])->name('home.index');
  Route::get('/home/edit', [HomeController::class, 'edit'])->name('home.edit');
  Route::put('/home', [HomeController::class, 'update'])->name('home.update');

  Route::get('/design', [DesignController::class, 'index'])->name('design.index');
  Route::get('/design/edit', [DesignController::class, 'edit'])->name('design.edit');
  Route::put('/design', [DesignController::class, 'update'])->name('design.update');

  Route::get('/construction', [ConstructionController::class, 'index'])->name('construction.index');
  Route::get('/construction/edit', [ConstructionController::class, 'edit'])->name('construction.edit');
  Route::put('/construction', [ConstructionController::class, 'update'])->name('construction.update');

  Route::get('/contact', [ContactController::class, 'index'])->name('contact.index');
  Route::get('/contact/edit', [ContactController::class, 'edit'])->name('contact.edit');
  Route::put('/contact', [ContactController::class, 'update'])->name('contact.update');

  Route::get('/portfolio', [PortfolioController::class, 'index'])->name('portfolio.index');
  Route::post('/portfolio', [PortfolioController::class, 'store'])->name('portfolio.store');
  Route::delete('/portfolio/{image}', [PortfolioController::class, 'destroy'])->name('portfolio.destroy');

  Route::resource('posts', PostsController::class)->except('edit');
  Route::resource('post_contenidos', PostContenidosController::class)->only('store', 'update', 'destroy');
  Route::post('/post_contenidos/{post_contenido}', [PostContenidosController::class, 'update'])->name('post_contenidos.update2');
});

resources/views/layouts/_errors.blade.php
@if (count($errors))
	<div class="form-group">
		<div class="alert alert-danger">
			<ul>
				@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
				@endforeach
			</ul>
		</div><!-- alert -->
	</div><!-- form-group -->
@endif

resources/views/layouts/_messages.blade.php
@if(session('success'))
  <div class="alert alert-success alert-dismissable fade show">
    <strong>¡Éxito!</strong> {{ session('success') }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div><!-- alert -->
@endif

@if(session()->has('alert'))
  <div class="alert alert-warning alert-dismissable fade show">
    <strong>¡Alerta!</strong> {{ session()->get('alert')}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
@endif

resources/views/layouts/headpanel.blade.php
<!-- ########## START: HEAD PANEL ########## -->
<div class="br-header">
  <div class="br-header-left">
    <div class="navicon-left hidden-md-down"><a id="btnLeftMenu" href=""><i class="icon ion-navicon-round"></i></a></div>
    <div class="navicon-left hidden-lg-up"><a id="btnLeftMenuMobile" href=""><i class="icon ion-navicon-round"></i></a></div>
  </div><!-- br-header-left -->
  <div class="br-header-right">
    <nav class="nav">
      <div class="dropdown">
        <a href="" class="nav-link nav-link-profile" data-toggle="dropdown">
          @if( Auth::check() )
            <span class="logged-name hidden-md-down">{{ Auth::user()->name }}</span>
          @endif 
          <img src="{{ asset('/img/empresa/logo_dh.jpg') }}" class="wd-32 rounded-circle" alt="">
          <span class="square-10 bg-success"></span>
        </a>
        <div class="dropdown-menu dropdown-menu-header wd-200">
          <ul class="list-unstyled user-profile-nav">
            <li><a href="{{ route('logout') }}"><i class="icon ion-power"></i> Cerrar Sesión</a></li>
          </ul>
        </div><!-- dropdown-menu -->
      </div><!-- dropdown -->
    </nav>
    {{-- <div class="navicon-right">
      <a id="btnRightMenu" href="" class="pos-relative">
        <i class="icon ion-chatbox"></i>
        <!-- start: if statement -->
        <!-- end: if statement -->
      </a>
    </div><!-- navicon-right --> --}}
  </div><!-- br-header-right -->
</div><!-- br-header -->
<!-- ########## END: HEAD PANEL ########## -->

resources/views/layouts/leftpanel.blade.php
<div class="br-logo">
  <a style="width: 80%; margin: 0 auto;" href="/usuarios">
    <img src="/img/empresa/logo_left_panel.png" class="w-100">
  </a>
</div><!-- br-logo -->
<div class="br-sideleft overflow-y-auto">
  @include ('layouts.navigation')
  @if(session()->get('nivel_id') == 0 || session()->get('nivel_id') == 1)
      
      {{-- @include ('layouts.infosummary')  --}}

  @endif                      
</div><!-- br-sideleft-menu -->

resources/views/layouts/mainpanel.blade.php
<div class="br-mainpanel">

  @yield ('pageheader')

<div class="br-pagebody">
    <!-- content goes here... -->
    <div id="app">
        @yield ('contentpanel')
    </div>
</div>

</div><!-- br-mainpanel -->

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="{{ env('APP_DESCRIPTION') }}">
    <meta name="author" content="{{ env('APP_AUTHOR') }}">
    <link rel="shortcut icon" href="{{ asset('/favicon.ico') }}" type="image/png">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta http-equiv="refresh" content="10000;url={{ route('logout') }}" />

    <title>DH Admin</title>

    @yield ('styles')

    <!-- CSS -->
    {{-- <link href="{{ asset('/css/app.css') }}" rel="stylesheet"> --}}
    <link href="/bracketv2/css/bracket.min.css" rel="stylesheet">

  </head>

  <body class="leftpanel-collapsed collapsed-menu" oncontextmenu="return false;">
    <div id="app">
      <!-- Preloader -->
      <div id="preloader" style="position: fixed;">
        <div id="status"><i class="fa fa-spinner fa-spin"></i></div>
      </div>

      <section>
        @include ('layouts.leftpanel')
        @include ('layouts.headpanel')
        @include ('layouts.mainpanel')
        @include ('layouts.rightpanel')
      </section>
    </div>

    @yield('scripts')
    <!-- JS -->
    <script src="{{ asset('/js/app.js') }}"></script>
    <script src="/bracketv2/js/bracket.js"></script>

    @yield('jquery')

    @yield('vue')

  </body>
</html>

resources/views/layouts/navigation.blade.php
<label class="sidebar-label pd-x-15 mg-t-20">MENÚ DE OPCIONES</label>
<div class="br-sideleft-menu">

  {{-- Configuración --}}
  <a href="#" class="br-menu-link">
    <div class="br-menu-item">
      <i class="menu-item-icon fa fa-pencil tx-20"></i>
      <span class="menu-item-label">Editar Website</span>
      <i class="menu-item-arrow fa fa-angle-down"></i>
    </div><!-- menu-item -->
  </a><!-- br-menu-link -->
  <ul class="br-menu-sub nav flex-column">
    <li class="nav-item"><a href="{{ route('home.index') }}" class="nav-link">Home</a></li>
    <li class="nav-item"><a href="{{ route('contact.index') }}" class="nav-link">Contact</a></li>
    <li class="nav-item"><a href="{{ route('construction.index') }}" class="nav-link">Construction</a></li>
    <li class="nav-item"><a href="{{ route('design.index') }}" class="nav-link">Design</a></li>
    <li class="nav-item"><a href="{{ route('portfolio.index') }}" class="nav-link">Portfolio</a></li>
    <li class="nav-item"><a href="{{ route('posts.index') }}" class="nav-link">Posts</a></li>
  </ul>

  {{-- Configuración --}}
  <a href="#" class="br-menu-link">
    <div class="br-menu-item">
      <i class="menu-item-icon ion-ios-gear tx-24"></i>
      <span class="menu-item-label">Configuración</span>
      <i class="menu-item-arrow fa fa-angle-down"></i>
    </div><!-- menu-item -->
  </a><!-- br-menu-link -->
  <ul class="br-menu-sub nav flex-column">
    <li class="nav-item"><a href="{{ route('users.index') }}" class="nav-link">Usuarios</a></li>
  </ul>

  {{-- Landing Page --}}
  <a href="{{ route('website.home') }}" class="br-menu-link" target="_blank">
    <div class="br-menu-item">
      <i class="menu-item-icon icon ion-monitor tx-24"></i>
      <span class="menu-item-label">Sitio Web</span>
    </div><!-- menu-item -->
  </a><!-- br-menu-link -->
    

</div><!-- br-sideleft-menu -->

resources/views/layouts/rightpanel.blade.php
<!-- ########## START: RIGHT PANEL ########## -->
<div class="br-sideright">
  <ul class="nav nav-tabs sidebar-tabs" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" role="tab" href="#ordenes-pendientes"><i class="icon ion-ios-contact-outline tx-24"></i></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" role="tab" href="#ordenes-proceso"><i class="icon ion-ios-folder-outline tx-22"></i></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" role="tab" href="#ordenes-canceladas"><i class="icon ion-ios-calendar-outline tx-24"></i></a>
    </li>
  </ul><!-- sidebar-tabs -->

  <!-- Tab panes -->
  <div class="tab-content">

    <div class="tab-pane pos-absolute a-0 mg-t-60 overflow-y-auto active" id="ordenes-pendientes" role="tabpanel">
      <label class="sidebar-label pd-x-25 mg-t-25">ÓRDENES PENDIENTES</label>
    </div><!-- #ordenes-pendientes -->

    <div class="tab-pane pos-absolute a-0 mg-t-60 overflow-y-auto" id="ordenes-proceso" role="tabpanel">
      <label class="sidebar-label pd-x-25 mg-t-25">ÓRDENES EN PROCESO</label>
    </div><!-- #ordenes-proceso -->

    <div class="tab-pane pos-absolute a-0 mg-t-60 overflow-y-auto" id="ordenes-canceladas" role="tabpanel">
      <label class="sidebar-label pd-x-25 mg-t-25">ÓRDENES CANCELADAS</label>
    </div>

  </div><!-- tab-content -->
</div><!-- br-sideright -->
<!-- ########## END: RIGHT PANEL ########## --->